services:
  trainer:
    container_name: trainer
    hostname: trainer
    image: registry.cn-hangzhou.aliyuncs.com/joybo/lora-scripts:v2025.04.12-action
    ports:
      - "28000:28000"
    networks:
      - trainer
    volumes:
      - ./ComfyUI/models:/models
      - ./huggingface:/app/huggingface
      - ./output:/app/output
    environment:
      - HF_HOME=huggingface
      - HF_ENDPOINT=https://hf-mirror.com
      - PYTHONUTF8=1
      - HF_HOME=/app
    security_opt:
      - "label=type:nvidia_container_t"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0','1']
              capabilities: [gpu]

networks:
  trainer:
    driver: bridge
    name: trainer
