services:
  lota-scripts:
    image: registry.cn-hangzhou.aliyuncs.com/joybo/lota-scripts:v2025.4.12-action
    container_name: lota-scripts
    hostname: lota-scripts
    environment:
      - TZ=Asia/Shanghai
      # - NVIDIA_VISIBLE_DEVICES=0
    volumes:
      - ./:./app/lora-scripts
    ports:
      - "28000:28000"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            # device_ids: ['0']
            capabilities: [gpu]
    stdin_open: true
    tty: true
    restart: no
    networks:
      - lora-scripts

networks:
  lora-scripts:
    driver: bridge
    name: lora-scripts
