FROM nvcr.io/nvidia/cuda:12.8.1-cudnn-runtime-ubuntu24.04
ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y wget net-tools curl iputils-ping git git-lfs tree curl && apt clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app
WORKDIR /app
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b -p /app/miniconda && rm -rf Miniconda3-latest-Linux-x86_64.sh
RUN /app/miniconda/bin/conda init
ENV PATH=/app/miniconda/bin:$PATH

RUN echo yes | conda create --name sd-scripts python=3.12
SHELL ["conda", "run", "-n", "sd-scripts", "/bin/bash", "-c"]

RUN git clone https://github.com/kohya-ss/sd-scripts.git
WORKDIR /app/sd-scripts
RUN wget https://huggingface.co/czmahi/xformers-windows-torch2.8-cu128-py312/resolve/main/xformers-0.0.30%2B3abeaa9e.d20250427-cp312-cp312-win_amd64.whl?download=true -O xformers-0.0.30%2B3abeaa9e.d20250427-cp312-cp312-win_amd64.whl && pip install xformers-0.0.30%2B3abeaa9e.d20250427-cp312-cp312-win_amd64.whl --no-deps && rm -rf xformers-0.0.30%2B3abeaa9e.d20250427-cp312-cp312-win_amd64.whl && pip cache purge
RUN pip install -U torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128 && pip install -r requirements.txt && pip cache purge

RUN rm -rf /etc/apt/sources.list && rm -rf /etc/apt/sources.list.d/*ubuntu* && wget https://github.com/IAMJOYBO/lora-scripts/raw/refs/heads/main/sources-24.04.list -O /etc/apt/sources.list
RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple && pip config set install.trusted-host mirrors.aliyun.com

ENTRYPOINT ["tail", "-f", "/dev/null"]
