FROM nvcr.io/nvidia/cuda:12.6.3-cudnn-runtime-ubuntu24.04
ENV TZ=Asia/Shanghai
ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y wget net-tools curl iputils-ping git git-lfs tree curl && apt clean && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /app
WORKDIR /app
RUN wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh && bash Miniconda3-latest-Linux-x86_64.sh -b -p /app/conda && rm -rf Miniconda3-latest-Linux-x86_64.sh
RUN /app/conda/bin/conda init

RUN conda create --name sd-scripts python=3.12
SHELL ["conda", "run", "-n", "sd-scripts", "/bin/bash", "-c"]
RUN conda activate sd-scripts

RUN git clone https://github.com/kohya-ss/sd-scripts.git
WORKDIR /app/sd-scripts
RUN pip install -U xformers torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126 && pip install -r requirements.txt && pip cache pruge

ENTRYPOINT ["tail", "-f", "/dev/null"]
